name: extended_image_library
description: package library for extended_image, extended_text and extended_text_field, provide common base class.
version: 3.1.4
homepage: https://github.com/fluttercandies/extended_image_library

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  crypto: ^3.0.0
  flutter:
    sdk: flutter
  http_client_helper: ^2.0.2
  path: ^1.7.0
  path_provider: ^2.0.1





