name: extended_image_library
description: package library for extended_image, extended_text and extended_text_field, provide common base class.
version: 0.4.0-nullsafety.2
homepage: https://github.com/fluttercandies/extended_image_library

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  crypto: ^3.0.0
  path: ^1.8.0
  path_provider: ^2.0.0
  http_client_helper: ^0.3.1
