name: extended_image_library
description: package library for extended_image, extended_text and extended_text_field, provide common base class.
version: 4.0.1
homepage: https://github.com/fluttercandies/extended_image_library

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  crypto: ^3.0.0
  flutter:
    sdk: flutter
  http_client_helper: ^3.0.0
  js: ^0.6.7
  path: ^1.7.0  
  path_provider: ^2.0.1
  web: ^0.3.0  






